import type { SSRManifest } from "astro";
import { App } from "astro/app";
import { handle } from "@astrojs/cloudflare/handler";

// Derived from `site` in astro.config.mjs so there is a single source of truth.
const CANONICAL_HOST = new URL(import.meta.env.SITE).host;

// Hostnames that should permanently redirect to the canonical domain.
// Version-preview URLs (<version>-<name>.workers.dev) are intentionally
// left alone so deploy previews keep working.
const LEGACY_HOSTS = new Set([
	`www.${CANONICAL_HOST}`,
	"vangaurd-collaboration-ts.yawriv.workers.dev",
]);

// Cloudflare's edge stamps every real request with `cf-visitor: {"scheme":"http"|"https"}`.
// `wrangler dev` does not, and it also presents request.url as the canonical
// route host over plain http, so reading the scheme from this header (rather
// than url.protocol) is what keeps local previews from redirect-looping.
const visitorUsedHttp = (request: Request) =>
	request.headers.get("cf-visitor")?.includes('"http"') ?? false;

export function createExports(manifest: SSRManifest) {
	const app = new App(manifest);
	// The adapter's handler is typed against its own copy of @cloudflare/workers-types,
	// which is structurally incompatible with the runtime types generated by
	// `wrangler types`. Loosen the signature at this one boundary.
	const render = handle as unknown as (
		manifest: SSRManifest,
		app: App,
		request: Request,
		env: Env,
		ctx: ExecutionContext,
	) => Promise<Response>;

	return {
		default: {
			async fetch(request, env, ctx) {
				const url = new URL(request.url);

				// Force https and the canonical host in a single hop.
				if (visitorUsedHttp(request) || LEGACY_HOSTS.has(url.host)) {
					url.protocol = "https:";
					if (LEGACY_HOSTS.has(url.host)) url.host = CANONICAL_HOST;
					return Response.redirect(url.toString(), 301);
				}

				return render(manifest, app, request, env, ctx);
			},
		} satisfies ExportedHandler<Env>,
	};
}
